name: Rocen
description: "A minimal workspace capture engine."
publish_to: 'none'

version: 0.3.0

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.9
  cryptography: ^2.7.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_staggered_grid_view: ^0.7.0
  file_picker: ^8.0.0
  photo_manager: ^3.3.0
  url_launcher: ^6.3.2
  http: ^1.6.0
  share_plus: ^12.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png